COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   kslow (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file containing a single slow K+ Channel description from a cortical layer V pyramidal neuron, described in Keren, N., Peled, N., and Korngr ... 
   /channelml/channel_type/@name = kslow 
   /channelml/channel_type/status/@value = in_progress 
   /channelml/channel_type/status/contributor/name = Boris Marin 
   /channelml/channel_type/authorList/modelAuthor[1]/name = Mara Almog 
   /channelml/channel_type/authorList/modelAuthor[2]/name = Alon Korngreen 
   /channelml/channel_type/authorList/modelTranslator/name = Boris Marin 
   /channelml/channel_type/authorList/modelTranslator/email = borismarin -at- gmail.com 
   /channelml/channel_type/publication/comment = Model transcribed from this article 
   /channelml/channel_type/publication/fullTitle = Keren, N., Peled, N., and Korngreen, A. (2005). Constraining compartmental models using multiple voltage recordings and genetic algorithms. Journal of ... 
   /channelml/channel_type/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/pubmed/16093338 
   /channelml/channel_type/parameters/parameter[1]/@name = vshift 
   /channelml/channel_type/parameters/parameter[1]/@value = 0 
   /channelml/channel_type/parameters/parameter[2]/@name = v05a 
   /channelml/channel_type/parameters/parameter[2]/@value = -14.3 
   /channelml/channel_type/parameters/parameter[3]/@name = za 
   /channelml/channel_type/parameters/parameter[3]/@value = 14.6 
   /channelml/channel_type/parameters/parameter[4]/@name = v05b 
   /channelml/channel_type/parameters/parameter[4]/@value = -58 
   /channelml/channel_type/parameters/parameter[5]/@name = zb 
   /channelml/channel_type/parameters/parameter[5]/@value = -11 
   /channelml/channel_type/parameters/parameter[6]/@name = a0 
   /channelml/channel_type/parameters/parameter[6]/@value = 0.0052 
   /channelml/channel_type/parameters/parameter[7]/@name = a1 
   /channelml/channel_type/parameters/parameter[7]/@value = 11.1 
   /channelml/channel_type/parameters/parameter[8]/@name = a2 
   /channelml/channel_type/parameters/parameter[8]/@value = 13.1 
   /channelml/channel_type/parameters/parameter[9]/@name = a3 
   /channelml/channel_type/parameters/parameter[9]/@value = 0.01938 
   /channelml/channel_type/parameters/parameter[10]/@name = a4 
   /channelml/channel_type/parameters/parameter[10]/@value = -1.27 
   /channelml/channel_type/parameters/parameter[11]/@name = a5 
   /channelml/channel_type/parameters/parameter[11]/@value = 71 
   /channelml/channel_type/parameters/parameter[12]/@name = a6 
   /channelml/channel_type/parameters/parameter[12]/@value = -0.0053 
   /channelml/channel_type/parameters/parameter[13]/@name = b0 
   /channelml/channel_type/parameters/parameter[13]/@value = 360 
   /channelml/channel_type/parameters/parameter[14]/@name = b11 
   /channelml/channel_type/parameters/parameter[14]/@value = 1010 
   /channelml/channel_type/parameters/parameter[15]/@name = b2 
   /channelml/channel_type/parameters/parameter[15]/@value = -75 
   /channelml/channel_type/parameters/parameter[16]/@name = b3 
   /channelml/channel_type/parameters/parameter[16]/@value = 48 
   /channelml/channel_type/parameters/parameter[17]/@name = b4 
   /channelml/channel_type/parameters/parameter[17]/@value = 23.7 
   /channelml/channel_type/parameters/parameter[18]/@name = b5 
   /channelml/channel_type/parameters/parameter[18]/@value = -54 
   /channelml/channel_type/parameters/parameter[19]/@name = bb0 
   /channelml/channel_type/parameters/parameter[19]/@value = 2350 
   /channelml/channel_type/parameters/parameter[20]/@name = bb1 
   /channelml/channel_type/parameters/parameter[20]/@value = 1380 
   /channelml/channel_type/parameters/parameter[21]/@name = bb2 
   /channelml/channel_type/parameters/parameter[21]/@value = 0.01118 
   /channelml/channel_type/parameters/parameter[22]/@name = bb3 
   /channelml/channel_type/parameters/parameter[22]/@value = -210 
   /channelml/channel_type/parameters/parameter[23]/@name = bb4 
   /channelml/channel_type/parameters/parameter[23]/@value = 0.0306 
   /channelml/channel_type/parameters/parameter[24]/@name = temp 
   /channelml/channel_type/parameters/parameter[24]/@value = 21 
   /channelml/channel_type/parameters/parameter[25]/@name = q10 
   /channelml/channel_type/parameters/parameter[25]/@value = 2.3 
   /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
   /channelml/channel_type/current_voltage_relation/@ion = k 
   /channelml/channel_type/current_voltage_relation/@default_gmax = 0 
   /channelml/channel_type/current_voltage_relation/@default_erev = -100 
   /channelml/channel_type/current_voltage_relation/q10_settings[1]/@q10_factor = 2.3 
   /channelml/channel_type/current_voltage_relation/q10_settings[1]/@gate = a 
   /channelml/channel_type/current_voltage_relation/q10_settings[1]/@experimental_temp = 21 
   /channelml/channel_type/current_voltage_relation/q10_settings[2]/@q10_factor = 1 
   /channelml/channel_type/current_voltage_relation/q10_settings[2]/@gate = b 
   /channelml/channel_type/current_voltage_relation/q10_settings[2]/@experimental_temp = 21 
   /channelml/channel_type/current_voltage_relation/gate[1]/@name = a 
   /channelml/channel_type/current_voltage_relation/gate[1]/@instances = 2 
   /channelml/channel_type/current_voltage_relation/gate[1]/closed_state/@id = ac 
   /channelml/channel_type/current_voltage_relation/gate[1]/open_state/@id = a 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@name = alpha 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@from = ac 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@to = a 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[1]/@expr = a0*(v-a1)/(1-exp(-(v-a1)/a2)) 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@name = beta 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@from = a 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@to = ac 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[1]/transition[2]/@expr = a3*exp(-(v-a4)/a5)+a6/temp_adj_a 
   /channelml/channel_type/current_voltage_relation/gate[2]/@name = b 
   /channelml/channel_type/current_voltage_relation/gate[2]/@instances = 1 
   /channelml/channel_type/current_voltage_relation/gate[2]/closed_state/@id = bc 
   /channelml/channel_type/current_voltage_relation/gate[2]/open_state[1]/@id = b 
   /channelml/channel_type/current_voltage_relation/gate[2]/open_state[1]/@fraction = 0.5 
   /channelml/channel_type/current_voltage_relation/gate[2]/open_state[2]/@id = b1 
   /channelml/channel_type/current_voltage_relation/gate[2]/open_state[2]/@fraction = 0.5 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[1]/@name = tau 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[1]/@from = bc 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[1]/@to = b 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[1]/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[1]/@expr = b0+(b11+b4*(v-b5))*exp(-(v-b2)*(v-b2)/(b3*b3)) 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[1]/@name = inf 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[1]/@from = bc 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[1]/@to = b 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[1]/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[1]/@expr = 1/(1 + exp(-(v-v05b)/zb)) 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[2]/@name = tau 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[2]/@from = bc 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[2]/@to = b1 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[2]/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course[2]/@expr = bb0+bb1*exp(-bb2*v)+bb3*exp(-bb4*v) 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[2]/@name = inf 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[2]/@from = bc 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[2]/@to = b1 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[2]/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state[2]/@expr = 1/(1 + exp(-(v-v05b)/zb)) 

// File from which this was generated: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/kslow/KslowChannel.xml

// XSL file with mapping to simulator: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/kslow/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file containing a single slow K+ Channel description from a cortical layer V pyramidal neuron, described in Keren, N., Peled, N., and Korngreen, A. (2005). Constraining compartmental models using multiple voltage recordings and genetic algorithms. Journal of neurophysiology, 94(6), 3730–42.
ENDCOMMENT

TITLE Channel: kslow

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX kslow
    USEION k READ ek WRITE ik VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    RANGE gmax, gion
    
    RANGE ainf, atau
    
    RANGE binf, btau
    
    RANGE b1inf, b1tau
    
    RANGE vshift
    RANGE v05a
    RANGE za
    RANGE v05b
    RANGE zb
    RANGE a0
    RANGE a1
    RANGE a2
    RANGE a3
    RANGE a4
    RANGE a5
    RANGE a6
    RANGE b0
    RANGE b11
    RANGE b2
    RANGE b3
    RANGE b4
    RANGE b5
    RANGE bb0
    RANGE bb1
    RANGE bb2
    RANGE bb3
    RANGE bb4
    RANGE temp
    RANGE q10
}

PARAMETER { 
      

    gmax = 0 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
    vshift = 0 : Note units of this will be determined by its usage in the generic functions

    v05a = -14.3 : Note units of this will be determined by its usage in the generic functions

    za = 14.6 : Note units of this will be determined by its usage in the generic functions

    v05b = -58 : Note units of this will be determined by its usage in the generic functions

    zb = -11 : Note units of this will be determined by its usage in the generic functions

    a0 = 0.0052 : Note units of this will be determined by its usage in the generic functions

    a1 = 11.1 : Note units of this will be determined by its usage in the generic functions

    a2 = 13.1 : Note units of this will be determined by its usage in the generic functions

    a3 = 0.01938 : Note units of this will be determined by its usage in the generic functions

    a4 = -1.27 : Note units of this will be determined by its usage in the generic functions

    a5 = 71 : Note units of this will be determined by its usage in the generic functions

    a6 = -0.0053 : Note units of this will be determined by its usage in the generic functions

    b0 = 360 : Note units of this will be determined by its usage in the generic functions

    b11 = 1010 : Note units of this will be determined by its usage in the generic functions

    b2 = -75 : Note units of this will be determined by its usage in the generic functions

    b3 = 48 : Note units of this will be determined by its usage in the generic functions

    b4 = 23.7 : Note units of this will be determined by its usage in the generic functions

    b5 = -54 : Note units of this will be determined by its usage in the generic functions

    bb0 = 2350 : Note units of this will be determined by its usage in the generic functions

    bb1 = 1380 : Note units of this will be determined by its usage in the generic functions

    bb2 = 0.01118 : Note units of this will be determined by its usage in the generic functions

    bb3 = -210 : Note units of this will be determined by its usage in the generic functions

    bb4 = 0.0306 : Note units of this will be determined by its usage in the generic functions

    temp = 21 : Note units of this will be determined by its usage in the generic functions

    q10 = 2.3 : Note units of this will be determined by its usage in the generic functions

}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of k
    ek (mV)
    ? The outward flow of ion: k calculated by rate equations...
    ik (mA/cm2)
    
    
    gion (S/cm2)
    ainf
    atau (ms)
    binf
    btau (ms)
    b1inf
    b1tau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
        
    gion = gmax * (a
^2) * (( (0.5*b) + (0.5*b1) )
^1)      

    ik = gion*(v - ek)
            

}



INITIAL {
    
    ek = -100
        
    rates(v)
    a = ainf
        b = binf
        b1 = b1inf
        
    
}
    
STATE {
    a
    b
    b1
    
}



DERIVATIVE states {
    rates(v)
    a' = (ainf - a)/atau
            b' = (binf - b)/btau
            b1' = (b1inf - b1)/b1tau
            

}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta
, temp_adj_a
, temp_adj_b
    
    : NOT USING TABLE: as there are some changable parameters (vshiftv05azav05bzba0a1a2a3a4a5a6b0b11b2b3b4b5bb0bb1bb2bb3bb4tempq10)
    : which may be different on different sections, using a TABLE for computing these values can lead to errors.
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
            
    temp_adj_a = 2.3^((celsius - 21)/10)
                        
    temp_adj_b = 1^((celsius - 21)/10)
                        
            
                
           

        
    ?      ***  Adding rate equations for gate: a  ***
         
    ? Found a generic form of the rate equation for alpha, using expression: a0*(v-a1)/(1-exp(-(v-a1)/a2))
    alpha = a0*(v-a1)/(1-exp(-(v-a1)/a2))
        
     
    ? Found a generic form of the rate equation for beta, using expression: a3*exp(-(v-a4)/a5)+a6/temp_adj_a
    beta = a3*exp(-(v-a4)/a5)+a6/temp_adj_a
        
    atau = 1/(temp_adj_a*(alpha + beta))
    ainf = alpha/(alpha + beta)
    


    ?     *** Finished rate equations for gate: a ***
    

    
            
                
           

        
    ?      ***  Adding rate equations for gate: b  ***
         
    ? Found a generic form of the rate equation for tau, using expression: b0+(b11+b4*(v-b5))*exp(-(v-b2)*(v-b2)/(b3*b3))
    tau = b0+(b11+b4*(v-b5))*exp(-(v-b2)*(v-b2)/(b3*b3))
        
    btau = tau/temp_adj_b
     
    ? Found a generic form of the rate equation for inf, using expression: 1/(1 + exp(-(v-v05b)/zb))
    inf = 1/(1 + exp(-(v-v05b)/zb))
        
    binf = inf
     
    ? Found a generic form of the rate equation for tau, using expression: bb0+bb1*exp(-bb2*v)+bb3*exp(-bb4*v)
    tau = bb0+bb1*exp(-bb2*v)+bb3*exp(-bb4*v)
        
    b1tau = tau/temp_adj_b
     
    ? Found a generic form of the rate equation for inf, using expression: 1/(1 + exp(-(v-v05b)/zb))
    inf = 1/(1 + exp(-(v-v05b)/zb))
        
    b1inf = inf
    


    ?     *** Finished rate equations for gate: b ***
    

         

}


UNITSON


