COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   na (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file containing a single Na Channel description from a cortical layer V pyramidal neuron, described in Keren, N., Peled, N., and Korngreen,  ... 
   /channelml/channel_type/@name = na 
   /channelml/channel_type/status/@value = in_progress 
   /channelml/channel_type/status/contributor/name = Boris Marin 
   /channelml/channel_type/authorList/modelAuthor[1]/name = Mara Almog 
   /channelml/channel_type/authorList/modelAuthor[2]/name = Alon Korngreen 
   /channelml/channel_type/authorList/modelTranslator/name = Boris Marin 
   /channelml/channel_type/authorList/modelTranslator/email = borismarin -at- gmail.com 
   /channelml/channel_type/publication/comment = Model transcribed from this article 
   /channelml/channel_type/publication/fullTitle = Keren, N., Peled, N., and Korngreen, A. (2005). Constraining compartmental models using multiple voltage recordings and genetic algorithms. Journal of ... 
   /channelml/channel_type/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/pubmed/16093338 
   /channelml/channel_type/parameters/parameter[1]/@name = vshiftm 
   /channelml/channel_type/parameters/parameter[1]/@value = -5 
   /channelml/channel_type/parameters/parameter[2]/@name = vshifth 
   /channelml/channel_type/parameters/parameter[2]/@value = -10 
   /channelml/channel_type/parameters/parameter[3]/@name = taum_scale 
   /channelml/channel_type/parameters/parameter[3]/@value = 1 
   /channelml/channel_type/parameters/parameter[4]/@name = tauh_scale 
   /channelml/channel_type/parameters/parameter[4]/@value = 1 
   /channelml/channel_type/parameters/parameter[5]/@name = a1 
   /channelml/channel_type/parameters/parameter[5]/@value = 0.058 
   /channelml/channel_type/parameters/parameter[6]/@name = a2 
   /channelml/channel_type/parameters/parameter[6]/@value = 0.114 
   /channelml/channel_type/parameters/parameter[7]/@name = a3 
   /channelml/channel_type/parameters/parameter[7]/@value = -36 
   /channelml/channel_type/parameters/parameter[8]/@name = a4 
   /channelml/channel_type/parameters/parameter[8]/@value = 28 
   /channelml/channel_type/parameters/parameter[9]/@name = v05m 
   /channelml/channel_type/parameters/parameter[9]/@value = -38 
   /channelml/channel_type/parameters/parameter[10]/@name = km 
   /channelml/channel_type/parameters/parameter[10]/@value = 10 
   /channelml/channel_type/parameters/parameter[11]/@name = i1 
   /channelml/channel_type/parameters/parameter[11]/@value = 0.28 
   /channelml/channel_type/parameters/parameter[12]/@name = i2 
   /channelml/channel_type/parameters/parameter[12]/@value = 16.7 
   /channelml/channel_type/parameters/parameter[13]/@name = i3 
   /channelml/channel_type/parameters/parameter[13]/@value = -60 
   /channelml/channel_type/parameters/parameter[14]/@name = i4 
   /channelml/channel_type/parameters/parameter[14]/@value = 25 
   /channelml/channel_type/parameters/parameter[15]/@name = v05h 
   /channelml/channel_type/parameters/parameter[15]/@value = -66 
   /channelml/channel_type/parameters/parameter[16]/@name = kh 
   /channelml/channel_type/parameters/parameter[16]/@value = -6 
   /channelml/channel_type/parameters/parameter[17]/@name = temp 
   /channelml/channel_type/parameters/parameter[17]/@value = 21 
   /channelml/channel_type/parameters/parameter[18]/@name = q10 
   /channelml/channel_type/parameters/parameter[18]/@value = 2.3 
   /channelml/channel_type/parameters/parameter[19]/@name = vmin 
   /channelml/channel_type/parameters/parameter[19]/@value = -120 
   /channelml/channel_type/parameters/parameter[20]/@name = vmax 
   /channelml/channel_type/parameters/parameter[20]/@value = 100 
   /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
   /channelml/channel_type/current_voltage_relation/@ion = na 
   /channelml/channel_type/current_voltage_relation/@default_gmax = 0 
   /channelml/channel_type/current_voltage_relation/@default_erev = 60 
   /channelml/channel_type/current_voltage_relation/q10_settings/@q10_factor = 2.3 
   /channelml/channel_type/current_voltage_relation/q10_settings/@experimental_temp = 21 
   /channelml/channel_type/current_voltage_relation/gate[1]/@name = m 
   /channelml/channel_type/current_voltage_relation/gate[1]/@instances = 3 
   /channelml/channel_type/current_voltage_relation/gate[1]/closed_state/@id = mc 
   /channelml/channel_type/current_voltage_relation/gate[1]/open_state/@id = m 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@name = tau 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@from = mc 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@to = m 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@expr = a1+a2*exp(-((v+vshiftm-a3)/a4)^2) 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@name = inf 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@from = mc 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@to = m 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@expr = 1/(1+exp(-(v+vshiftm-v05m)/km)) 
   /channelml/channel_type/current_voltage_relation/gate[2]/@name = h 
   /channelml/channel_type/current_voltage_relation/gate[2]/@instances = 1 
   /channelml/channel_type/current_voltage_relation/gate[2]/closed_state/@id = hc 
   /channelml/channel_type/current_voltage_relation/gate[2]/open_state/@id = h 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@name = tau 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@from = hc 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@to = h 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@expr = i1+i2*exp(-((v+vshifth-i3)/i4)^2) 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@name = inf 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@from = hc 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@to = h 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@expr = 1/(1+exp(-(v+vshifth-v05h)/kh)) 

// File from which this was generated: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/na/NaChannel.xml

// XSL file with mapping to simulator: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/na/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file containing a single Na Channel description from a cortical layer V pyramidal neuron, described in Keren, N., Peled, N., and Korngreen, A. (2005). Constraining compartmental models using multiple voltage recordings and genetic algorithms. Journal of neurophysiology, 94(6), 3730-42.
ENDCOMMENT

TITLE Channel: na

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX na
    USEION na READ ena WRITE ina VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    RANGE gmax, gion
    
    RANGE minf, mtau
    
    RANGE hinf, htau
    
    RANGE vshiftm
    RANGE vshifth
    RANGE taum_scale
    RANGE tauh_scale
    RANGE a1
    RANGE a2
    RANGE a3
    RANGE a4
    RANGE v05m
    RANGE km
    RANGE i1
    RANGE i2
    RANGE i3
    RANGE i4
    RANGE v05h
    RANGE kh
    RANGE temp
    RANGE q10
    RANGE vmin
    RANGE vmax
}

PARAMETER { 
      

    gmax = 0 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
    vshiftm = -5 : Note units of this will be determined by its usage in the generic functions

    vshifth = -10 : Note units of this will be determined by its usage in the generic functions

    taum_scale = 1 : Note units of this will be determined by its usage in the generic functions

    tauh_scale = 1 : Note units of this will be determined by its usage in the generic functions

    a1 = 0.058 : Note units of this will be determined by its usage in the generic functions

    a2 = 0.114 : Note units of this will be determined by its usage in the generic functions

    a3 = -36 : Note units of this will be determined by its usage in the generic functions

    a4 = 28 : Note units of this will be determined by its usage in the generic functions

    v05m = -38 : Note units of this will be determined by its usage in the generic functions

    km = 10 : Note units of this will be determined by its usage in the generic functions

    i1 = 0.28 : Note units of this will be determined by its usage in the generic functions

    i2 = 16.7 : Note units of this will be determined by its usage in the generic functions

    i3 = -60 : Note units of this will be determined by its usage in the generic functions

    i4 = 25 : Note units of this will be determined by its usage in the generic functions

    v05h = -66 : Note units of this will be determined by its usage in the generic functions

    kh = -6 : Note units of this will be determined by its usage in the generic functions

    temp = 21 : Note units of this will be determined by its usage in the generic functions

    q10 = 2.3 : Note units of this will be determined by its usage in the generic functions

    vmin = -120 : Note units of this will be determined by its usage in the generic functions

    vmax = 100 : Note units of this will be determined by its usage in the generic functions

}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of na
    ena (mV)
    ? The outward flow of ion: na calculated by rate equations...
    ina (mA/cm2)
    
    
    gion (S/cm2)
    minf
    mtau (ms)
    hinf
    htau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
        
    gion = gmax * (m
^3) * (h
^1)      

    ina = gion*(v - ena)
            

}



INITIAL {
    
    ena = 60
        
    rates(v)
    m = minf
        h = hinf
        
    
}
    
STATE {
    m
    h
    
}



DERIVATIVE states {
    rates(v)
    m' = (minf - m)/mtau
            h' = (hinf - h)/htau
            

}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta
, temp_adj_m
, temp_adj_h
    
    : NOT USING TABLE: as there are some changable parameters (vshiftmvshifthtaum_scaletauh_scalea1a2a3a4v05mkmi1i2i3i4v05hkhtempq10vminvmax)
    : which may be different on different sections, using a TABLE for computing these values can lead to errors.
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
                 

    temp_adj_m = 2.3^((celsius - 21)/10)     

    temp_adj_h = 2.3^((celsius - 21)/10)
            
                
           

        
    ?      ***  Adding rate equations for gate: m  ***
         
    ? Found a generic form of the rate equation for tau, using expression: a1+a2*exp(-((v+vshiftm-a3)/a4)^2)
    tau = a1+a2*exp(-((v+vshiftm-a3)/a4)^2)
        
    mtau = tau/temp_adj_m
     
    ? Found a generic form of the rate equation for inf, using expression: 1/(1+exp(-(v+vshiftm-v05m)/km))
    inf = 1/(1+exp(-(v+vshiftm-v05m)/km))
        
    minf = inf
    


    ?     *** Finished rate equations for gate: m ***
    

    
            
                
           

        
    ?      ***  Adding rate equations for gate: h  ***
         
    ? Found a generic form of the rate equation for tau, using expression: i1+i2*exp(-((v+vshifth-i3)/i4)^2)
    tau = i1+i2*exp(-((v+vshifth-i3)/i4)^2)
        
    htau = tau/temp_adj_h
     
    ? Found a generic form of the rate equation for inf, using expression: 1/(1+exp(-(v+vshifth-v05h)/kh))
    inf = 1/(1+exp(-(v+vshifth-v05h)/kh))
        
    hinf = inf
    


    ?     *** Finished rate equations for gate: h ***
    

         

}


UNITSON


