COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   cad (Type: Ion concentration, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/ion/@name = ca 
   /channelml/ion/@charge = 2 
   /channelml/ion/@role = SignallingSubstance 
   /channelml/ion_concentration/@name = cad 
   /channelml/ion_concentration/status/@value = stable 
   /channelml/ion_concentration/status/contributor/name = Boris Marin 
   /channelml/ion_concentration/notes = Intracellular [Ca2+] decay 
   /channelml/ion_concentration/authorList/modelAuthor[1]/name = Alain Destexhe 
   /channelml/ion_concentration/authorList/modelAuthor[2]/name = Mara Almog 
   /channelml/ion_concentration/authorList/modelAuthor[3]/name = Alon Korngreen 
   /channelml/ion_concentration/authorList/modelTranslator/name = Boris Marin 
   /channelml/ion_concentration/authorList/modelTranslator/email = borismarin -at- gmail.com 
   /channelml/ion_concentration/publication/comment = The .mod file in modelDB refers to: Destexhe, A. Babloyantz, A. and Sejnowski, TJ. Ionic mechanisms for intrinsic slow oscillations in thalamic relay  ... 
   /channelml/ion_concentration/publication/fullTitle = Keren, N., Peled, N., and Korngreen, A. (2005). Constraining compartmental models using multiple voltage recordings and genetic algorithms. Journal of ... 
   /channelml/ion_concentration/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/pubmed/16093338 
   /channelml/ion_concentration/ion_species/@name = ca 
   /channelml/ion_concentration/decaying_pool_model/@resting_conc = 1e-10 
   /channelml/ion_concentration/decaying_pool_model/@decay_constant = 80 
   /channelml/ion_concentration/decaying_pool_model/pool_volume_info/@shell_thickness = 0.1e-4 

// File from which this was generated: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/cad/CaDecay.xml

// XSL file with mapping to simulator: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/cad/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

    

? Creating ion concentration

TITLE Channel: cad

COMMENT
    Intracellular [Ca2+] decay
ENDCOMMENT


UNITS {
    (mV) = (millivolt)
    (mA) = (milliamp)
    (um) = (micrometer)
    (l) = (liter)
    (molar) = (1/liter)
    (mM) = (millimolar)
}

    
NEURON {
    SUFFIX cad
    USEION ca READ ica WRITE cai VALENCE 2
    
    RANGE cai
    
    RANGE rest_conc
    
    
    RANGE tau
    
    RANGE thickness, F


    RANGE total_current
    RANGE volume_pool
    
    
    
}

ASSIGNED {

    ica (mA/cm2)
    diam (um)
    area (um)
}

INITIAL {
    
        
    LOCAL pi, shell_inner_diam, cylinderLen, circumference, circumference_shell, volumeOuter, volumeInner, volumeSph, volumeCyl

    pi = 3.14159265

    shell_inner_diam = diam - (2*thickness)


    ?  Volume of the pool if it is a shell inside a sphere of diameter diam

    volumeSph = (diam*diam*diam) * pi / 6 - (shell_inner_diam*shell_inner_diam*shell_inner_diam)* pi / 6


    ? Volume of the pool if it is a cylinder

    circumference = diam * pi
    circumference_shell = shell_inner_diam * pi

    cylinderLen = area/circumference

    volumeOuter = (diam * diam/4) * pi * cylinderLen
    volumeInner = (shell_inner_diam * shell_inner_diam/4) * pi * cylinderLen
    volumeCyl = volumeOuter - volumeInner

    if ((area - (pi * diam * diam)) < 1e-3 && (area - (pi * diam * diam)) > -1e-3 ) {

        ? Assume the segment is a sphere
        

        volume_pool = volumeSph
        
    } else {

        ? assume segment is a cylinder
        

        volume_pool = volumeCyl
    }

    cai = rest_conc

}

PARAMETER {

    total_current
    rest_conc = 0.0001 (mM)
          
    
    tau = 80 (ms)
   
    F = 96494 (C)
    
    thickness = 0.1 (um)   
                
    volume_pool
    
    
}

STATE {

    cai (mM)

}

BREAKPOINT {

    SOLVE conc METHOD derivimplicit
    

}

DERIVATIVE conc {
    
    LOCAL thickness_cm, surf_area_cm2, volume_cm3 ? Note, normally dimensions are in um, but curr dens is in mA/cm2, etc
    
    thickness_cm = thickness *(1e-4)
    surf_area_cm2 = area * 1e-8
    volume_cm3 = volume_pool * 1e-12
    
    total_current = ica * surf_area_cm2


    cai' =  ((-1 * total_current)/(2 * F * volume_cm3)) - ((cai - rest_conc)/tau)
    

}

