COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   iA (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file containing a single fast K+ Channel description from a cortical layer V pyramidal neuron, described in Keren, N., Peled, N., and Korngr ... 
   /channelml/channel_type/@name = iA 
   /channelml/channel_type/status/@value = in_progress 
   /channelml/channel_type/status/contributor/name = Boris Marin 
   /channelml/channel_type/authorList/modelAuthor[1]/name = Mara Almog 
   /channelml/channel_type/authorList/modelAuthor[2]/name = Alon Korngreen 
   /channelml/channel_type/authorList/modelTranslator/name = Boris Marin 
   /channelml/channel_type/authorList/modelTranslator/email = borismarin -at- gmail.com 
   /channelml/channel_type/publication/comment = Model transcribed from this article 
   /channelml/channel_type/publication/fullTitle = Keren, N., Peled, N., and Korngreen, A. (2005). Constraining compartmental models using multiple voltage recordings and genetic algorithms. Journal of ... 
   /channelml/channel_type/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/pubmed/16093338 
   /channelml/channel_type/parameters/parameter[1]/@name = v05n 
   /channelml/channel_type/parameters/parameter[1]/@value = -47 
   /channelml/channel_type/parameters/parameter[2]/@name = v05l 
   /channelml/channel_type/parameters/parameter[2]/@value = -66 
   /channelml/channel_type/parameters/parameter[3]/@name = kn 
   /channelml/channel_type/parameters/parameter[3]/@value = 29 
   /channelml/channel_type/parameters/parameter[4]/@name = kl 
   /channelml/channel_type/parameters/parameter[4]/@value = -10 
   /channelml/channel_type/parameters/parameter[5]/@name = qq 
   /channelml/channel_type/parameters/parameter[5]/@value = 5 
   /channelml/channel_type/parameters/parameter[6]/@name = tq 
   /channelml/channel_type/parameters/parameter[6]/@value = -55 
   /channelml/channel_type/parameters/parameter[7]/@name = temp 
   /channelml/channel_type/parameters/parameter[7]/@value = 21 
   /channelml/channel_type/parameters/parameter[8]/@name = q10 
   /channelml/channel_type/parameters/parameter[8]/@value = 2.3 
   /channelml/channel_type/parameters/parameter[9]/@name = vmin 
   /channelml/channel_type/parameters/parameter[9]/@value = -120 
   /channelml/channel_type/parameters/parameter[10]/@name = vmax 
   /channelml/channel_type/parameters/parameter[10]/@value = 100 
   /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
   /channelml/channel_type/current_voltage_relation/@ion = k 
   /channelml/channel_type/current_voltage_relation/@default_gmax = 0 
   /channelml/channel_type/current_voltage_relation/@default_erev = -100 
   /channelml/channel_type/current_voltage_relation/q10_settings/@q10_factor = 2.3 
   /channelml/channel_type/current_voltage_relation/q10_settings/@experimental_temp = 21 
   /channelml/channel_type/current_voltage_relation/gate[1]/@name = n 
   /channelml/channel_type/current_voltage_relation/gate[1]/@instances = 4 
   /channelml/channel_type/current_voltage_relation/gate[1]/closed_state/@id = nc 
   /channelml/channel_type/current_voltage_relation/gate[1]/open_state/@id = n 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@name = tau 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@from = nc 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@to = n 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[1]/time_course/@expr = 0.34+0.92*exp(-((v+71)/59)^2) 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@name = inf 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@from = nc 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@to = n 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[1]/steady_state/@expr = 1/(1 + exp(-(v-v05n)/kn)) 
   /channelml/channel_type/current_voltage_relation/gate[2]/@name = l 
   /channelml/channel_type/current_voltage_relation/gate[2]/@instances = 1 
   /channelml/channel_type/current_voltage_relation/gate[2]/closed_state/@id = lc 
   /channelml/channel_type/current_voltage_relation/gate[2]/open_state/@id = l 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@name = tau 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@from = lc 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@to = l 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[2]/time_course/@expr = 8+49*exp(-((v+73)/23)^2) 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@name = inf 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@from = lc 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@to = l 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate[2]/steady_state/@expr = 1/(1 + exp(-(v-v05l)/kl)) 

// File from which this was generated: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/iA/KfastChannel.xml

// XSL file with mapping to simulator: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/iA/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file containing a single fast K+ Channel description from a cortical layer V pyramidal neuron, described in Keren, N., Peled, N., and Korngreen, A. (2005). Constraining compartmental models using multiple voltage recordings and genetic algorithms. Journal of neurophysiology, 94(6), 3730–42.
ENDCOMMENT

TITLE Channel: iA

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX iA
    USEION k READ ek WRITE ik VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    RANGE gmax, gion
    
    RANGE ninf, ntau
    
    RANGE linf, ltau
    
    RANGE v05n
    RANGE v05l
    RANGE kn
    RANGE kl
    RANGE qq
    RANGE tq
    RANGE temp
    RANGE q10
    RANGE vmin
    RANGE vmax
}

PARAMETER { 
      

    gmax = 0 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
    v05n = -47 : Note units of this will be determined by its usage in the generic functions

    v05l = -66 : Note units of this will be determined by its usage in the generic functions

    kn = 29 : Note units of this will be determined by its usage in the generic functions

    kl = -10 : Note units of this will be determined by its usage in the generic functions

    qq = 5 : Note units of this will be determined by its usage in the generic functions

    tq = -55 : Note units of this will be determined by its usage in the generic functions

    temp = 21 : Note units of this will be determined by its usage in the generic functions

    q10 = 2.3 : Note units of this will be determined by its usage in the generic functions

    vmin = -120 : Note units of this will be determined by its usage in the generic functions

    vmax = 100 : Note units of this will be determined by its usage in the generic functions

}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of k
    ek (mV)
    ? The outward flow of ion: k calculated by rate equations...
    ik (mA/cm2)
    
    
    gion (S/cm2)
    ninf
    ntau (ms)
    linf
    ltau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
        
    gion = gmax * (n
^4) * (l
^1)      

    ik = gion*(v - ek)
            

}



INITIAL {
    
    ek = -100
        
    rates(v)
    n = ninf
        l = linf
        
    
}
    
STATE {
    n
    l
    
}



DERIVATIVE states {
    rates(v)
    n' = (ninf - n)/ntau
            l' = (linf - l)/ltau
            

}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta
, temp_adj_n
, temp_adj_l
    
    : NOT USING TABLE: as there are some changable parameters (v05nv05lknklqqtqtempq10vminvmax)
    : which may be different on different sections, using a TABLE for computing these values can lead to errors.
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
                 

    temp_adj_n = 2.3^((celsius - 21)/10)     

    temp_adj_l = 2.3^((celsius - 21)/10)
            
                
           

        
    ?      ***  Adding rate equations for gate: n  ***
         
    ? Found a generic form of the rate equation for tau, using expression: 0.34+0.92*exp(-((v+71)/59)^2)
    tau = 0.34+0.92*exp(-((v+71)/59)^2)
        
    ntau = tau/temp_adj_n
     
    ? Found a generic form of the rate equation for inf, using expression: 1/(1 + exp(-(v-v05n)/kn))
    inf = 1/(1 + exp(-(v-v05n)/kn))
        
    ninf = inf
    


    ?     *** Finished rate equations for gate: n ***
    

    
            
                
           

        
    ?      ***  Adding rate equations for gate: l  ***
         
    ? Found a generic form of the rate equation for tau, using expression: 8+49*exp(-((v+73)/23)^2)
    tau = 8+49*exp(-((v+73)/23)^2)
        
    ltau = tau/temp_adj_l
     
    ? Found a generic form of the rate equation for inf, using expression: 1/(1 + exp(-(v-v05l)/kl))
    inf = 1/(1 + exp(-(v-v05l)/kl))
        
    linf = inf
    


    ?     *** Finished rate equations for gate: l ***
    

         

}


UNITSON


