COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   iH (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file containing a single H Channel description from a cortical layer V pyramidal neuron, described in Keren, N., Peled, N., and Korngreen, A ... 
   /channelml/channel_type/@name = iH 
   /channelml/channel_type/status/@value = in_progress 
   /channelml/channel_type/status/contributor/name = Boris Marin 
   /channelml/channel_type/authorList/modelAuthor[1]/name = Mara Almog 
   /channelml/channel_type/authorList/modelAuthor[2]/name = Alon Korngreen 
   /channelml/channel_type/authorList/modelTranslator/name = Boris Marin 
   /channelml/channel_type/authorList/modelTranslator/email = borismarin -at- gmail.com 
   /channelml/channel_type/publication[1]/comment = Model transcribed from this article 
   /channelml/channel_type/publication[1]/fullTitle = Keren, N., Peled, N., and Korngreen, A. (2005). Constraining compartmental models using multiple voltage recordings and genetic algorithms. Journal of ... 
   /channelml/channel_type/publication[1]/pubmedRef = http://www.ncbi.nlm.nih.gov/pubmed/16093338 
   /channelml/channel_type/publication[2]/comment = Based on 
   /channelml/channel_type/publication[2]/fullTitle = Williams, S. R., and Stuart, G. J. (2000). Site Independence of EPSP Time Course Is Mediated by Dendritic Ih in Neocortical Pyramidal Neurons. J Neuro ... 
   /channelml/channel_type/publication[2]/pubmedRef = http://www.ncbi.nlm.nih.gov/pubmed/10805715 
   /channelml/channel_type/parameters/parameter[1]/@name = v05 
   /channelml/channel_type/parameters/parameter[1]/@value = -91 
   /channelml/channel_type/parameters/parameter[2]/@name = k 
   /channelml/channel_type/parameters/parameter[2]/@value = 6 
   /channelml/channel_type/parameters/parameter[3]/@name = t0 
   /channelml/channel_type/parameters/parameter[3]/@value = 0.0003933 
   /channelml/channel_type/parameters/parameter[4]/@name = t1 
   /channelml/channel_type/parameters/parameter[4]/@value = -0.0249 
   /channelml/channel_type/parameters/parameter[5]/@name = t2 
   /channelml/channel_type/parameters/parameter[5]/@value = 0.0877 
   /channelml/channel_type/parameters/parameter[6]/@name = t3 
   /channelml/channel_type/parameters/parameter[6]/@value = 0.062 
   /channelml/channel_type/parameters/parameter[7]/@name = temp 
   /channelml/channel_type/parameters/parameter[7]/@value = 21 
   /channelml/channel_type/parameters/parameter[8]/@name = q10 
   /channelml/channel_type/parameters/parameter[8]/@value = 2.3 
   /channelml/channel_type/parameters/parameter[9]/@name = vmin 
   /channelml/channel_type/parameters/parameter[9]/@value = -120 
   /channelml/channel_type/parameters/parameter[10]/@name = vmax 
   /channelml/channel_type/parameters/parameter[10]/@value = 100 
   /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
   /channelml/channel_type/current_voltage_relation/@ion = h 
   /channelml/channel_type/current_voltage_relation/@charge = 1 
   /channelml/channel_type/current_voltage_relation/@default_gmax = 0 
   /channelml/channel_type/current_voltage_relation/@default_erev = -33 
   /channelml/channel_type/current_voltage_relation/q10_settings/@q10_factor = 2.3 
   /channelml/channel_type/current_voltage_relation/q10_settings/@experimental_temp = 22 
   /channelml/channel_type/current_voltage_relation/gate/@name = a 
   /channelml/channel_type/current_voltage_relation/gate/@instances = 1 
   /channelml/channel_type/current_voltage_relation/gate/closed_state/@id = ac 
   /channelml/channel_type/current_voltage_relation/gate/open_state/@id = a 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@name = tau 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@from = ac 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@to = a 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@expr = 1/(t0*exp(t1*v)+t2*exp(t3*v)) 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@name = inf 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@from = ac 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@to = a 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@expr = 1/(1 + exp((v-v05)/k)) 
   /channelml/channel_type/impl_prefs/table_settings/@max_v = 100 
   /channelml/channel_type/impl_prefs/table_settings/@min_v = -120 
   /channelml/channel_type/impl_prefs/table_settings/@table_divisions = 199 

// File from which this was generated: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/iH/HChannel.xml

// XSL file with mapping to simulator: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/iH/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file containing a single H Channel description from a cortical layer V pyramidal neuron, described in Keren, N., Peled, N., and Korngreen, A. (2005). Constraining compartmental models using multiple voltage recordings and genetic algorithms. Journal of neurophysiology, 94(6), 3730-42.
ENDCOMMENT

TITLE Channel: iH

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX iH
    USEION h READ eh WRITE ih VALENCE 1 ? reversal potential of ion is read, outgoing current is written
           
        
    RANGE gmax, gion
    
    RANGE ainf, atau
    
    RANGE v05
    RANGE k
    RANGE t0
    RANGE t1
    RANGE t2
    RANGE t3
    RANGE temp
    RANGE q10
    RANGE vmin
    RANGE vmax
}

PARAMETER { 
      

    gmax = 0 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
    v05 = -91 : Note units of this will be determined by its usage in the generic functions

    k = 6 : Note units of this will be determined by its usage in the generic functions

    t0 = 0.0003933 : Note units of this will be determined by its usage in the generic functions

    t1 = -0.0249 : Note units of this will be determined by its usage in the generic functions

    t2 = 0.0877 : Note units of this will be determined by its usage in the generic functions

    t3 = 0.062 : Note units of this will be determined by its usage in the generic functions

    temp = 21 : Note units of this will be determined by its usage in the generic functions

    q10 = 2.3 : Note units of this will be determined by its usage in the generic functions

    vmin = -120 : Note units of this will be determined by its usage in the generic functions

    vmax = 100 : Note units of this will be determined by its usage in the generic functions

}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of h
    eh (mV)
    ? The outward flow of ion: h calculated by rate equations...
    ih (mA/cm2)
    
    
    gion (S/cm2)
    ainf
    atau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
        
    gion = gmax * (a
^1)      

    ih = gion*(v - eh)
            

}



INITIAL {
    
    eh = -33
        
    rates(v)
    a = ainf
        
    
}
    
STATE {
    a
    
}



DERIVATIVE states {
    rates(v)
    a' = (ainf - a)/atau
            

}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta
, temp_adj_a
    
    : NOT USING TABLE: as there are some changable parameters (v05kt0t1t2t3tempq10vminvmax)
    : which may be different on different sections, using a TABLE for computing these values can lead to errors.
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
                 

    temp_adj_a = 2.3^((celsius - 22)/10)
            
                
           

        
    ?      ***  Adding rate equations for gate: a  ***
         
    ? Found a generic form of the rate equation for tau, using expression: 1/(t0*exp(t1*v)+t2*exp(t3*v))
    tau = 1/(t0*exp(t1*v)+t2*exp(t3*v))
        
    atau = tau/temp_adj_a
     
    ? Found a generic form of the rate equation for inf, using expression: 1/(1 + exp((v-v05)/k))
    inf = 1/(1 + exp((v-v05)/k))
        
    ainf = inf
    


    ?     *** Finished rate equations for gate: a ***
    

         

}


UNITSON


