COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   sk (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file containing a single SK Channel description, from a model of a Globus Pallidus neuron described in Deister, C. A., Chan, C. S., Surmeier ... 
   /channelml/channel_type/@name = sk 
   /channelml/channel_type/status/@value = in_progress 
   /channelml/channel_type/status/contributor/name = Boris Marin 
   /channelml/channel_type/authorList/modelAuthor/name = Chris Deister 
   /channelml/channel_type/authorList/modelTranslator/name = Boris Marin 
   /channelml/channel_type/authorList/modelTranslator/email = borismarin -at- gmail.com 
   /channelml/channel_type/publication/comment = Model originally described in this article 
   /channelml/channel_type/publication/fullTitle = Mercer JN, Chan CS, Tkatch T, Held J, Surmeier DJ. Nav1.6 sodium channels are critical to pacemaking and fast spiking in globus pallidus neurons.,J Ne ... 
   /channelml/channel_type/publication/pubmedRef = http://www.ncbi.nlm.nih.gov/pubmed/18057213 
   /channelml/channel_type/modelDBref/comment = Original model version (but with different parameter values) in ModelDB 
   /channelml/channel_type/modelDBref/modelName = Nav1.6 sodium channel model in globus pallidus neurons (Mercer et al. 2007) 
   /channelml/channel_type/modelDBref/uri = http://senselab.med.yale.edu/modeldb/ShowModel.asp?model=105385&amp;file=\gp\mod\sk_gp.mod 
   /channelml/channel_type/parameters/parameter[1]/@name = a0 
   /channelml/channel_type/parameters/parameter[1]/@value = 1.3e4 
   /channelml/channel_type/parameters/parameter[2]/@name = b0 
   /channelml/channel_type/parameters/parameter[2]/@value = 0.06 
   /channelml/channel_type/parameters/parameter[3]/@name = Cq10 
   /channelml/channel_type/parameters/parameter[3]/@value = 3 
   /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
   /channelml/channel_type/current_voltage_relation/@ion = k 
   /channelml/channel_type/current_voltage_relation/@default_gmax = 0 
   /channelml/channel_type/current_voltage_relation/@default_erev = -100 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@name = Calcium 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@ion = ca 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@charge = 2 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@variable_name = ca_conc 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@min_conc = 1e-12 
   /channelml/channel_type/current_voltage_relation/conc_dependence/@max_conc = 1 
   /channelml/channel_type/current_voltage_relation/q10_settings/@q10_factor = 3 
   /channelml/channel_type/current_voltage_relation/q10_settings/@experimental_temp = 22 
   /channelml/channel_type/current_voltage_relation/gate/@name = w 
   /channelml/channel_type/current_voltage_relation/gate/@instances = 1 
   /channelml/channel_type/current_voltage_relation/gate/closed_state/@id = wc 
   /channelml/channel_type/current_voltage_relation/gate/open_state/@id = wo 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@name = tau 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@from = wc 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@to = wo 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@expr = 1/((a0 * ((1e6)*ca_conc)^4) + b0) 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@name = inf 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@from = wc 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@to = wo 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@expr = 1 / (1 + b0/(a0 * ((1e6)*ca_conc)^4)) 

// File from which this was generated: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/sk/SKChannel.xml

// XSL file with mapping to simulator: /Users/borismarin/git/korngreen-pyramidal/neuroConstruct/cellMechanisms/sk/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file containing a single SK Channel description, from a model of a Globus Pallidus neuron described in Deister, C. A., Chan, C. S., Surmeier, D. J., & Wilson, C. J. (2009). Calcium-activated SK channels influence voltage-gated ion channels to determine the precision of firing in globus pallidus neurons. J Neurosci, 29(26), 8452–61. doi:10.1523/JNEUROSCI.0576-09.2009 
ENDCOMMENT

TITLE Channel: sk

UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX sk
    USEION k READ ek WRITE ik VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    USEION ca READ cai VALENCE 2 ? internal concentration of ion is read

    
    RANGE gmax, gion
    
    RANGE woinf, wotau
    
    RANGE a0
    RANGE b0
    RANGE Cq10
}

PARAMETER { 
      

    gmax = 0 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
    a0 = 1.3e4 : Note units of this will be determined by its usage in the generic functions

    b0 = 0.06 : Note units of this will be determined by its usage in the generic functions

    Cq10 = 3 : Note units of this will be determined by its usage in the generic functions

}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of k
    ek (mV)
    ? The outward flow of ion: k calculated by rate equations...
    ik (mA/cm2)
          

    ? The internal concentration of ion: ca is used in the rate equations...
    cai (mM)   
    
    
    gion (S/cm2)
    woinf
    wotau (ms)
    
}

BREAKPOINT { 
    SOLVE states METHOD derivimplicit
    gion = gmax * (wo
^1)      

    ik = gion*(v - ek)
            

}



INITIAL {
    
    ek = -100
        
    settables(v,cai)
    wo = woinf
        
    
}
    
STATE {
    wo
    
}



DERIVATIVE states {
    settables(v,cai)
    wo' = (woinf - wo)/wotau
            

}

PROCEDURE settables(v(mV), cai(mM)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta, ca_conc
, temp_adj_w
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
                 

    temp_adj_w = 3^((celsius - 22)/10)
    ? Gate depends on the concentration of ca
    ca_conc = cai ? In NEURON, the variable for the concentration  of ca is cai
    
            
                
           

        
    ?      ***  Adding rate equations for gate: w  ***
         
    ? Found a generic form of the rate equation for tau, using expression: 1/((a0 * ((1e6)*ca_conc)^4) + b0)
    
    ? Equations can depend on concentration. NEURON uses 'SI Units' internally for concentration, 
    ? but the ChannelML file is in Physiological Units...
    ca_conc = ca_conc / 1000000
    tau = 1/((a0 * ((1e6)*ca_conc)^4) + b0)
        
    ? Resetting concentration...
    ca_conc = ca_conc * 1000000
    
    wotau = tau/temp_adj_w
     
    ? Found a generic form of the rate equation for inf, using expression: 1 / (1 + b0/(a0 * ((1e6)*ca_conc)^4))
    
    ? Equations can depend on concentration. NEURON uses 'SI Units' internally for concentration, 
    ? but the ChannelML file is in Physiological Units...
    ca_conc = ca_conc / 1000000
    inf = 1 / (1 + b0/(a0 * ((1e6)*ca_conc)^4))
        
    ? Resetting concentration...
    ca_conc = ca_conc * 1000000
    
    woinf = inf
    


    ?     *** Finished rate equations for gate: w ***
    

         

}


UNITSON


